name: Altseed

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  doc:
    runs-on: windows-latest
    name: Doc
    steps:
    - uses: actions/checkout@v2

    - name: Update Submodules
      run: |
        choco install docfx
        git submodule update --init

    - name: Build
      run: |
        docfx --serve

    - name: Upload artifact
      continue-on-error: true
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test
        path: ./

